# Generated by Django 6.0.7 on 2026-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=180)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(max_length=160)),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('team', 'Team'), ('laboratory', 'Laboratory'), ('prototype', 'Prototype'), ('events', 'Events'), ('water_hyacinth', 'Water Hyacinth'), ('community', 'Community')], max_length=30)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'gallery images',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, upload_to='partners/')),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('partner_type', models.CharField(choices=[('academic', 'Academic'), ('research', 'Research'), ('government', 'Government'), ('ngo', 'NGO'), ('innovation', 'Innovation Support'), ('manufacturing', 'Manufacturing'), ('community', 'Community')], default='innovation', max_length=30)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EcoFem', max_length=80)),
                ('short_description', models.TextField(default='Developing affordable, biodegradable sanitary pads using processed water hyacinth fibres.')),
                ('project_story', models.TextField(blank=True)),
                ('mission', models.TextField(default='To develop accessible, sustainable and high-performing menstrual hygiene solutions while transforming environmental waste into useful resources.')),
                ('vision', models.TextField(default='A future where every woman and girl can access safe and affordable menstrual products without compromising the environment.')),
                ('values', models.TextField(default='Innovation\nSustainability\nDignity\nInclusivity\nQuality\nCommunity Impact', help_text='Enter one value per line.')),
                ('email', models.EmailField(blank=True, default='hello@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, default='Location to be confirmed', max_length=180)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('prototypes_developed', models.PositiveIntegerField(blank=True, help_text='Leave blank until a verified figure is available.', null=True)),
                ('tests_conducted', models.PositiveIntegerField(blank=True, help_text='Leave blank until a verified figure is available.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='team/')),
                ('role', models.CharField(max_length=120)),
                ('expertise', models.CharField(max_length=180)),
                ('short_bio', models.TextField(help_text='A concise biography for the profile page.')),
                ('professional_background', models.TextField(blank=True)),
                ('contribution', models.TextField(blank=True, help_text='What this person brings to EcoFem.')),
                ('leadership_story', models.TextField(blank=True, help_text='Optional founder/project leadership story.')),
                ('vision_for_ecofem', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_founder_or_lead', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='updates/')),
                ('short_description', models.CharField(max_length=320)),
                ('content', models.TextField()),
                ('publication_date', models.DateField()),
                ('author', models.CharField(blank=True, default='EcoFem Team', max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-publication_date', '-created_at'),
            },
        ),
    ]
